apiVersion: v1
kind: Service
metadata:
  name: ${project.build.finalName}
spec:
  type: LoadBalancer
  selector:
    app: ${project.build.finalName}
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: 30050
    name: http
